# Build and test CPAN module:  DataTableText

name: Test

on:
  push

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        sudo apt update
        sudo apt -y install build-essential tree
        sudo cpan -T install Data::Table::Text Module::Build Digest::SHA1 JSON
    - name: Test
      run: |
        tree
        perl Build.PL
        perl Build test

  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        curl http://strawberryperl.com/download/5.32.0.1/strawberry-perl-5.32.0.1-64bit.msi --output perl.msi
        msiexec /i perl.msi
        cpan -T install Data::Table::Text Module::Build Digest::SHA1 JSON

    - name: Test
      run: |
        perl lib/Data/Table/Text.pm

  mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        sudo cpan -T install Data::Table::Text Module::Build Digest::SHA1 JSON
    - name: Test
      run: |
        tree
        perl Build.PL
        perl Build test
